### ISSUE TITLE
Unable to build for Android: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by youssmak** [voxeet/voxeet-cordova-conferencekit#14]
**Describe the bug**
```
Exception in thread "main" java.lang.IllegalArgumentException
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
    at com.google.devtools.build.android.desugar.DefaultMethodClassFixer$DefaultMethodFinder.visit(DefaultMethodClassFixer.java:471)
    at org.objectweb.asm.ClassReader.accept(Unknown Source)
    at org.objectweb.asm.ClassReader.accept(Unknown Source)
    at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.defaultMethodsDefined(DefaultMethodClassFixer.java:319)
    at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:88)
    at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
    at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:85)
    at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
    at com.google.devtools.build.android.desugar.LambdaDesugaring.visitEnd(LambdaDesugaring.java:150)
    at org.objectweb.asm.ClassReader.accept(Unknown Source)
    at org.objectweb.asm.ClassReader.accept(Unknown Source)
    at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
    at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
    at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
    at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)
```

**Steps to Reproduce the Problem**

  1. install the latest version of the voxeet cordova plugin: 1.0.29
  2. build with cordova build android -- --gradleArg=-PcdvMinSdkVersion=19 --verbose

**Specifications**
  - cordova-cli 8.1.2
  - cordova-android 7.1.4
  - Android SDK platform-tools@28.0.1
  - Android SDK Build-tools@28.0.3
  - Android SDK-tools@26.1.1

**Comment by codlab** [comment]
Make sure that you have the following (at least)
- gradle wrapper version : `4.1`
- compileSdkVersion : `28`
- buildToolsVersion : `28.0.3`
- buildScript build gradle plugin : `3.0.0`

For referenchere is the sdk environment :
- build gradle plugin `3.3.0` (pas d’incidence directe, compat 3.+)
- external variables
```ext {
    buildToolsVersion = "28.0.3"
    minSdkVersion = 14
    compileSdkVersion = 28
    targetSdkVersion = 27
    supportLibVersion = "28.0.0"
    voxeetSdkVersion = "1.4.8"
    voxeetSdkToolkitVersion = "1.4.8"
}```

**Comment by youssmak** [comment]
FCM_VERSION: 17.3.4

Thks for the details.
I can build the android project again
