### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'voxeet.com.sdk.core.abs.AbstractConferenceSdkService voxeet.com.sdk.core.VoxeetSdk.getConferenceService()' on a null object reference

### ISSUE THREAD

**Issue by youssmak** [voxeet/voxeet-cordova-conferencekit#16]
**Describe the bug**

When i call Voxeet.leave() when i disconnect the user it raises sometimes an exception.
I will add a try / catch whenever i use Voxeet in my code but could you please avoid this exception to be raised ?

stacktrace
```
02-13 15:03:54.500  1581  1581 D KeyguardUpdateMonitor: received broadcast android.intent.action.BATTERY_CHANGED
02-13 15:03:54.500  1581  1581 W KeyguardUpdateMonitor: ACTION_BATTERY_CHANGED AMP: 500000; Volt: 5000000
02-13 15:03:54.503  1581  1581 V KeyguardUpdateMonitor: RefreshBatteryInfo isBatteryLow: 53
02-13 15:03:54.504  1581  1581 W KeyguardUpdateMonitor: ChargingSpeed  Wattage: 2500000 ST: 5000000 --> 7500000
02-13 15:03:54.504  1581  1581 I KgBattery: BatteryInfo updated:  2lPc0
02-13 15:03:54.504  1581  1581 W AppHandler: sendMessage with obj100
02-13 15:03:54.504  1581  1581 D KeyguardUpdateMonitor: handleBatteryUpdate
02-13 15:03:54.504  1581  1581 W HwKeyguardBottomArea: updateBatteryInfo : false  true
02-13 15:03:54.504  1581  1581 W KgBattery: getCharge info with type: text
02-13 15:03:54.506  1004  1004 D WifiService: onReceive, action:android.intent.action.BATTERY_CHANGED
02-13 15:03:54.506  1004  1004 D WifiService: ACTION_BATTERY_CHANGED pluggedType: 2
02-13 15:03:54.508  1581  1581 W HwLockScreenPanel: Handle message: 100
02-13 15:03:54.508  1581  1581 W HwLockScreenPanel: refreshBatteryInfo: null
02-13 15:03:54.509  1756  1756 I MsgReceiver: intent action: android.intent.action.BATTERY_CHANGED
02-13 15:03:54.674   919   986 W libc    : Set property "ril.hw_modem0.rssi" to "-103"
02-13 15:03:54.780 31411 31411 I HwSecImmHelper: mSecurityInputMethodService is null
02-13 15:03:54.895 31411 31411 D SystemWebChromeClient: http://localhost:8080/build/main.js: Line 899 : VideoconfService - clear data
02-13 15:03:54.896 31411 31411 I chromium: [INFO:CONSOLE(899)] "VideoconfService - clear data", source: http://localhost:8080/build/main.js (899)
02-13 15:03:54.925 31411 31616 D VoxeetCordova: execute: request leave
02-13 15:03:54.931 31411 31411 D AndroidRuntime: Shutting down VM
02-13 15:03:54.934 31411 31411 E AndroidRuntime: FATAL EXCEPTION: main
02-13 15:03:54.934 31411 31411 E AndroidRuntime: Process: com.app, PID: 31411
02-13 15:03:54.934 31411 31411 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'voxeet.com.sdk.core.abs.AbstractConferenceSdkService voxeet.com.sdk.core.VoxeetSdk.getConferenceService()' on a null object reference
02-13 15:03:54.934 31411 31411 E AndroidRuntime: 	at com.voxeet.toolkit.VoxeetCordova$17.run(VoxeetCordova.java:740)
02-13 15:03:54.934 31411 31411 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:808)
02-13 15:03:54.934 31411 31411 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:101)
02-13 15:03:54.934 31411 31411 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
02-13 15:03:54.934 31411 31411 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7529)
02-13 15:03:54.934 31411 31411 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-13 15:03:54.934 31411 31411 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
02-13 15:03:54.934 31411 31411 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
02-13 15:03:54.942  1004  3079 W ActivityManager:   Force finishing activity com.app/.MainActivity
02-13 15:03:54.951  1004  3328 I chatty  : uid=1000(system) AsyUploadThread expire 1 line
02-13 15:03:54.951 31411 31411 I Process : Sending signal. PID: 31411 SIG: 9
02-13 15:03:54.961   767  2437 E iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
02-13 15:03:54.964   767  2437 I chatty  : uid=0(root) engine identical 3 lines
02-13 15:03:54.964   767  2437 E iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
02-13 15:03:54.964   767  2437 I iMonitor: create: 901001001
02-13 15:03:54.964   767  2437 I iMonitor: send: 901001001
02-13 15:03:54.964   767  2437 E iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
02-13 15:03:54.964   767  2437 E iMonitor: FaultDetect: DUMPTOOL_PRINTF return.
02-13 15:03:54.970   761   787 E AwareLog: iawared: change_property_content open /proc/31411/task/31490/static_vip fail errno(2)!
02-13 15:03:54.990  1004  1148 D HwGameAssistantController: pid=1835, uid=10063, foreground=true
02-13 15:03:54.991  1004  1300 I chatty  : uid=1000(system) sManagerService expire 1 line
02-13 15:03:55.000 18585 31766 D WorkSource: Insert in WorkSource{} @ 0 uid 10016 name com.google.android.gms
02-13 15:03:55.008  1004  1304 I HwNetworkPolicy: onTransact, code = 203
02-13 15:03:55.009  1438  1532 I HwNetworkPolicyManager: getHwUidPolicy uid = 10063 policy = 0
02-13 15:03:55.011  1004  1304 I HwAudioService: now type = -1,reportForegroundAppType = 301,systemload = -1
02-13 15:03:55.012  1004  1304 I chatty  : uid=1000(system) Binder:1004_3 expire 1 line
02-13 15:03:55.015 18472 31770 D WorkSource: Insert in WorkSource{} @ 0 uid 10016 name com.google.android.gms
02-13 15:03:55.019  1004  1304 V BroadcastQueue: Finished with ordered broadcast BroadcastRecord{3160134 u0 android.intent.action.DROPBOX_ENTRY_ADDED}
02-13 15:03:55.029  1581  2147 D NetworkController.MobileSignalController(0): mSimSubId:0 onDataActivity: direction=3
``` 

**Expected Behaviour**

no fatal exception

**Minimalistic code (recommended)**
```
Voxeet.initializeToken(access_token, refresh_token)
    .then(() => Voxeet.defaultBuiltInSpeaker(true))
    .then(() => Voxeet.defaultVideo(true))
    .then(() => Voxeet.connect(new UserInfo(this.currentUser.id, this.currentUser.displayname, this.currentUser.avatar)))
    .then(() => Voxeet.create({conferenceAlias: confId})
    .then(result => Voxeet.join(result.conferenceId))
    .catch(err => console.log(error));
```

**Specifications**

* Version: Voxeet 1.0.28
* Platform: Android 8.0
* Subsystem: EMUI 8.0.0
* Hardware: Honor 7X

* cordova-cli 8.1.2
* cordova-android 7.1.4
* Android SDK platform-tools@28.0.1
* Android SDK Build-tools@28.0.3
* Android SDK-tools@26.1.1

**Comment by codlab** [comment]
In the meantime, avoid calling sdk methods without initializing first. This can happen in such case.

The best practice is to initialize the SDK first thing first even if the user is to be connected later

Also when providing accurate reproducing bug when doing so

**Comment by codlab** [comment]
Avoid assigning people not in charge of the Android side

**Comment by codlab** [comment]
A fix should be available really soon 👌

**Comment by youssmak** [comment]
thanks.
I have not assigned anyone nor added the "bug" label : https://github.com/voxeet/voxeet-cordova-conferencekit/blob/master/.github/ISSUE_TEMPLATE/report-an-issue.md

**Comment by codlab** [comment]
I'll look into it as well 👌

Le lun. 18 févr. 2019 à 09:37, Youssef Makboul <notifications@github.com> a
écrit :

**Comment by codlab** [comment]
The calls should be properly managed now. The SDK calls returning a promise will now fail if the SDK is not properly initialized

**Comment by codlab** [comment]
The issue is fixed, I'm closing it. Feel free to reopen in case it would be necessary to reuse it for the same contextual issue
