### ISSUE TITLE
Unable to build on Android

### ISSUE THREAD

**Issue by youssmak** [voxeet/voxeet-cordova-conferencekit#3]
cordova-cli
`8.0.0`

cordova-android
`android 6.4.0 `

build cmd
`cordova platform add android@6.4.0 && cordova build android -- --gradleArg=-PcdvMinSdkVersion=16 --verbose`

```
BUILD FAILED in 5s
37 actionable tasks: 4 executed, 33 up-to-date
Command finished with error code 1: */platforms/android/gradlew cdvBuildDebug,-b,/*/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Dorg.gradle.jvmargs=-Xmx2048m,-Pandroid.useDeprecatedNdk=true
(node:27556) UnhandledPromiseRejectionWarning: Error: */platforms/android/gradlew: Command failed with exit code 1 Error output:
Exception in thread "main" java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer$DefaultMethodFinder.visit(DefaultMethodClassFixer.java:471)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.defaultMethodsDefined(DefaultMethodClassFixer.java:319)
	at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:88)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:85)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at com.google.devtools.build.android.desugar.LambdaDesugaring.visitEnd(LambdaDesugaring.java:150)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at org.objectweb.asm.ClassVisitor.visitEnd(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)


FAILURE: Build failed with an exception.
```

**Comment by youssmak** [comment]
I have finally fixed it by fixing the fcm version of the push plugin
```
<variable name="FCM_VERSION" value="10.2.1" />
```
Maybe you could update the README ?
